# Generated by Django 3.1.6 on 2021-02-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
                ('start_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_data', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.CharField(db_index=True, max_length=256, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('survey_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256, verbose_name='Ответ')),
                ('result', models.BooleanField(default=False, verbose_name='Результат')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.question')),
                ('survey_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.survey')),
            ],
        ),
    ]
