# Generated by Django 3.1.6 on 2021-02-08 18:45

from django.db import migrations, models
import django.db.models.deletion
import survey_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название')),
                ('start_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_data', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.CharField(db_index=True, max_length=256, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='Пользователь')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('type', models.CharField(max_length=30, validators=[survey_list.models.question_type_validator])),
                ('survey_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.survey')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=128, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30, validators=[survey_list.models.question_type_validator])),
                ('question_text', models.CharField(max_length=300, verbose_name='Текст вопроса')),
                ('answer', models.CharField(max_length=256, verbose_name='Ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_list.submit')),
            ],
        ),
    ]
