# Generated by Django 3.1.6 on 2021-02-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey_title',
        ),
    ]
